- name: Configure netplan file
  hosts: servers
  become: true
  tasks:
    - name: Create netplan configuration file
      copy:
        content: |
          network:
            ethernets:
              ibp3s0f0:
                renderer: networkd
                addresses: ["{{ hostvars[inventory_hostname]['ip_address_ibp3s0f0'] }}/24"]
              ibp3s0f1:
                renderer: networkd
                addresses: ["{{ hostvars[inventory_hostname]['ip_address_ibp3s0f1'] }}/24"]
              ibP2p3s0f0:
                renderer: networkd
                addresses: ["{{ hostvars[inventory_hostname]['ip_address_ibP2p3s0f0'] }}/24"]
              ibP2p3s0f1:
                renderer: networkd
                addresses: ["{{ hostvars[inventory_hostname]['ip_address_ibP2p3s0f1'] }}/24"]
            version: 2
        dest: /etc/netplan/60-mlnx.yaml
        mode: '0644'
