---
- name: Install Zabbix Agent
  hosts: servers
  tasks:

  - name: Gather OS info
    setup:
      filter: ansible_distribution*

  - name: Install Zabbix Agent on RHEL
    block:
      - name: Add Zabbix Repo for RHEL
        command:
          cmd: rpm -Uvh https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-release-6.0-4.el7.noarch.rpm
        become: yes

      - name: Install Zabbix Agent
        yum:
          name: zabbix-agent
          state: latest
        become: yes

    when: ansible_distribution == "RedHat"

  - name: Install Zabbix Agent on Ubuntu 22.04
    block:
      - name: Add Zabbix Repo for Ubuntu 22.04
        command:
          cmd: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb -O /tmp/zabbix-release.deb
        become: yes

      - name: Install the Repo package
        apt:
          deb: /tmp/zabbix-release.deb
        become: yes

      - name: Update and install Zabbix Agent
        apt:
          name: zabbix-agent
          update_cache: yes
          state: latest
        become: yes

    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "22.04"

  - name: Install Zabbix Agent on Ubuntu 20.04
    block:
      - name: Add Zabbix Repo for Ubuntu 20.04
        command:
          cmd: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu20.04_all.deb -O /tmp/zabbix-release.deb
        become: yes

      - name: Install the Repo package
        apt:
          deb: /tmp/zabbix-release.deb
        become: yes

      - name: Update and install Zabbix Agent
        apt:
          name: zabbix-agent
          update_cache: yes
          state: latest
        become: yes

    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "20.04"

  - name: Restart and enable zabbix-agent service
    systemd:
      name: zabbix-agent
      state: restarted
      enabled: yes
    become: yes

