- name: Configure netplan file
  hosts: servers
  become: true
  tasks:
    - name: Create netplan configuration file
      copy:
        content: |
          network:
            ethernets:
              ibp3s0:
                renderer: networkd
                addresses: ["{{ hostvars[inventory_hostname]['ip_address_ibp3s0'] }}/24"]
              enp3s0f0s0:
                renderer: networkd
                addresses: ["{{ hostvars[inventory_hostname]['ip_address_enp3s0f0s0'] }}/24"]
              enp3s0f1s0:
                renderer: networkd
                addresses: ["{{ hostvars[inventory_hostname]['ip_address_enp3s0f1s0'] }}/24"]
            version: 2
        dest: /etc/netplan/60-mlnx.yaml
        mode: '0644'
