---
- name: Update Network Configuration for InfiniBand Interface
  hosts: all
  become: yes
  vars:
    ip_base: "1.1.82."

  tasks:
    - name: Debug hostname transformation
      debug:
        msg: "Hostname numeric part: {{ ansible_hostname | regex_replace('elsa', '') }}"

    - name: Set BOOTPROTO to no
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-ib0
        regexp: '^BOOTPROTO='
        line: 'BOOTPROTO=no'

    - name: Set IPADDR based on hostname
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-ib0
        regexp: '^IPADDR='
        line: "IPADDR={{ ip_base }}{{ '%02d' | format((ansible_hostname | regex_replace('elsa', '') | int)) }}"

    - name: Set PREFIX to 24
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-ib0
        regexp: '^PREFIX='
        line: 'PREFIX=24'

    - name: Set ONBOOT to yes
      ansible.builtin.lineinfile:
        path: /etc/sysconfig/network-scripts/ifcfg-ib0
        regexp: '^ONBOOT='
        line: 'ONBOOT=yes'

    - name: Restart network service
      ansible.builtin.systemd:
        name: network
        state: restarted
        daemon_reload: yes

